View(fatherhood)
shapiro.test(fatherhood$egg)
shapiro.test(fatherhood$emb)
shapiro.test(fatherhood$avconml)
shapiro.test(fatherhood$resp)

bf<-cbind(fatherhood, log(fatherhood$egg))
hist(bf$"log(fatherhood$egg)")
bf<-cbind(fatherhood, log10(fatherhood$emb))
hist(bf$"log10(fatherhood$emb)")

kruskal.test(egg ~ avconml, data=fatherhood)
kruskal.test(egg ~ resp, data=fatherhood)
kruskal.test(emb ~ resp, data=fatherhood)

egg<- glm(egg ~ andate, data=fatherhood)
glm(egg)
summary(egg)
egg<- glm(egg ~ avconml, data=fatherhood)
glm(egg)
summary(egg)
egg<- glm(egg ~ resp*emb, data=fatherhood)
glm(egg)
summary(egg)

(fatherhood$egg)
bf1<-as.factor(fatherhood$egg)
levels(bf1)
Sper_rep<-cbind(fatherhood$egg, bf1=as.factor(fatherhood$egg))
head(fatherhood)

bf1<-glm(egg ~ avconml + andate + resp + emb + resp*andate, data=fatherhood)
summary(bf1)
bf2<-glm(egg ~ avconml*andate + resp*andate +resp*avconml, data=fatherhood)
summary(bf2)  
bf3<-glm(emb ~ avconml + andate + resp + emb + resp*andate, data=fatherhood)
summary(bf3)
bf4<-glm(emb ~ avconml*andate + resp*andate +resp*avconml, data=fatherhood)
summary(bf4) 
